apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wa-gateway-media-pvc-new
  namespace: wa-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-sc
